id = "assembly"
name = "Assembly"
description = "Assembly support."
version = "0.0.2"
schema_version = 1
authors = ["Insidious Fiddler <contact@codycody31.dev>"]
repository = "https://github.com/Codycody31/zed-asm"

[language_servers.asm-lsp]
name = "AssemblyLS"
language = "Assembly"

[grammars.asm]
repository = "https://github.com/RubixDev/tree-sitter-asm"
commit = "b0306e9bb2ebe01c6562f1aef265cc42ccc53070"
